export const Archive = {
    constructionEffects:[
        './construction/dust1.svg',
        './construction/dust2.svg',
        './construction/dust3.svg',
        './construction/dust4.svg',
        './construction/dust5.svg',
        './construction/dust6.svg',
        './construction/dust7.svg',
    ],
    dusts:[
        './explosion/dust1.svg',
        './explosion/dust2.svg',
        './explosion/dust3.svg',
        './explosion/dust4.svg',
    ],
    explosions:[
        './explosion/explosion1.svg',
        './explosion/explosion2.svg',
        './explosion/explosion3.svg',
        './explosion/explosion4.svg',
        './explosion/explosion5.svg',
        './explosion/explosion6.svg',
        './explosion/explosion7.svg',
    ],
    skull:'./explosion/skull.svg',
    menu:{
        smartMenu:{
            tankSelection:'./menu/smartMenu/tankSelection.svg',
            hoverTankSelection:'./menu/smartMenu/tankSelectionHover.svg',
            cellSelection:'./menu/smartMenu/cellSelection.svg',
            hoverCellSelection:'./menu/smartMenu/cellSelectionHover.svg',
            multiCellSelection:'./menu/smartMenu/multiSelectionCell.svg',
        },
        amounts:[
            './menu/priceZero.svg',
            './menu/priceOne.svg',
            './menu/priceTwo.svg',
            './menu/priceThree.svg',
            './menu/priceFour.svg',
            './menu/priceFive.svg'
        ],
        abortButton:'./menu/AbortMenu.svg',
        searchMoneyButton:'./menu/SearchMoneyButton.svg',
        plusButton:'./menu/plusButton.svg',
        minButton:'./menu/minusButton.svg',
        energyButton:'./menu/energyButton.svg',
        smallingButton:'./menu/smallingMenu.svg',
        biggingButton:'./menu/biggingMenu.svg',
        bottomMenu:'./menu/bottomMenu.svg',
        backgroundButton:'./menu/backgroundMenu.svg',
        hoverBackgroundButton:'./menu/hoverBackgroundMenu.svg',
        selectabedBackgroundButton:'./menu/selectedBackgroundMenu.svg',
        powerButton:'./menu/powerMenu.svg',
        flagButton:'./menu/flagMenu.svg',
        healthButton:'./menu/healthMenu.svg',
        moneyButton:'./menu/moneyMenu.svg',
        speedMenu:'./menu/speedMenu.svg',
        showEnemies:'./menu/showEnemiesButton.svg',
        resetButton:'./menu/resetButton.svg',
        pauseButton:'./menu/pauseButton.svg',
        visionMenu:'./menu/visionMenu.svg',
        camouflageMenu:'./menu/camouflageMenu.svg',
        patrolButton:'./menu/patrolButton.svg',
        targetButton:'./menu/targetButton.svg',
        cancelButton:'./menu/cancelButton.svg',
        truckButton:'./menu/truckButton.svg',
    },
    missiles:[
        './tank/missile/missile.svg',
        './tank/missile/missile2.svg',
        './tank/missile/missile3.svg',
        './tank/missile/missile4.svg',
    ],
    cannons:[
        './tank/cannon.svg',
        './tank/cannon1.svg',
        './tank/cannon2.svg',
        './tank/cannon3.svg',
        './tank/cannon4.svg',
    ],
    diamonds:[
        './truck/diamonds/diamonds1.svg',
        './truck/diamonds/diamonds2.svg',
        './truck/diamonds/diamonds3.svg',
        './truck/diamonds/diamonds4.svg',
        './truck/diamonds/diamonds5.svg',
        './truck/diamonds/diamonds6.svg',
    ],
    destruction:{
        debris:'./tank/debris.svg',
        floorExplosion:'./tank/floorExplosionTrace.svg'
    },
    loading:'./loading.svg',
    hiddenCell:'./hiddenCell.svg',
    halfVisibleCell:'./halfVisibleCell.svg',
    selectionUnit:'./selectionUnit.svg',
    selectionCell:'./selectionCell.svg',
    cell:'./cell.svg',
    diamondCell:'./diamondCell.svg',
    flagCell:'./flagCell.svg',
    option:'./option.svg',
    direction:{
        target:'./direction/target.svg',
        moving:'./direction/motion.svg',
        patrol:'./direction/patrol2.svg'
    },
    building:{
        hq:{
            bottom:'./building/hqMiddle.svg',
            top:'./building/hqTop.svg',
            red:{
                field:'./building/hqRedCell.svg',
                area:'./building/redAreaEnergy.svg'
            },
            blue:{
                field:'./building/hqBlueCell.svg'
            },
            yellow:{
                field:'./building/hqYellowCell.svg'
            },
            purple:{
                field:'./building/hqPurpleCell.svg'
            },
        }
    },
    bonus:{
        strength:'./floor/strength.svg',
        speed:'./floor/speed.svg',
        health:'./floor/health.svg',
        poison:'./floor/poisonCell.svg',
        slow:'./floor/slowCell.svg',
        emptyMoney:'./floor/money.svg',
        fullMoney:'./floor/money2.svg',
    },
    lights:[
        './lights/light1.svg',
        './lights/light2.svg',
        './lights/light3.svg',
        './lights/light4.svg'
    ],
    nature:{
        clouds:[
            './nature/cloud1.svg',
            './nature/cloud2.svg',
            './nature/cloud3.svg',
            './nature/cloud4.svg',
            './nature/cloud5.svg',
        ],
        volcano:'./nature/volcano.svg',
        volcanaoAnimation:'./nature/volcanoAnimation.svg',
        diamondStone:'./nature/diamondStone.svg',
        stone:'./nature/stones.svg',
        sandStone:'./nature/sandStones.svg',
        puddle:'./nature/waterPuddle.svg',
        bush:'./nature/bush.svg',
        rock:'./nature/rock.svg',
        sandRock:'./nature/sandRock.svg',
        grass:'./nature/grass.svg',
        sand:'./nature/sand.svg',
        palmTree:'./nature/palmTree.svg',
        tree:'./nature/tree.svg',
        water:{
            leaf:'./nature/waterleaf.svg',
            middle:{
                background:'./nature/water.svg',
                wave:'./nature/wave.svg'
            },
        },
        diamond:'./nature/diamond.svg',
    },
    team:{
        red:{
            tank:'./tank/bottomTank.svg',
            turrel:'./tank/redTurrel.svg',
            truck:'./truck/truck.svg',
            hq:'./building/redHqBottom.svg',
            energy:'./building/redEnergyCell.svg',
            baseEnergy:'./building/redBaseEnergyCell.svg',
        },
        blue:{
            tank:'./tank/blueBottomTank.svg',
            turrel:'./tank/blueTurrel.svg',
            truck:'./truck/blueTruck.svg',
            hq:'./building/blueHqBottom.svg',
            energy:'./building/blueEnergyCell.svg',
            baseEnergy:'./building/blueBaseEnergyCell.svg',
        },
        yellow:{
            tank:'./tank/yellowBottomTank.svg',
            turrel:'./tank/yellowTurrel.svg',
            truck:'./truck/yellowTruck.svg',
            hq:'./building/yellowHqBottom.svg',
            energy:'./building/yellowEnergyCell.svg',
            baseEnergy:'./building/yellowBaseEnergyCell.svg',
        },purple:{
            tank:'./tank/purpleBottomTank.svg',
            turrel:'./tank/purpleTurrel.svg',
            truck:'./truck/purpleTruck.svg',
            hq:'./building/purpleHqBottom.svg',
            energy:'./building/purpleEnergyCell.svg',
            baseEnergy:'./building/purpleBaseEnergyCell.svg',
        }
    },
    wheel:'./tank/wheel.svg',
    wheels:[
        './tank/wheel1.svg',
        './tank/wheel2.svg',
        './tank/wheel3.svg',
        './tank/wheel4.svg',
        './tank/wheel5.svg',
        './tank/wheel6.svg',
        './tank/wheel7.svg',
        './tank/wheel8.svg',
    ]
};
