export enum RequestType {
	None = 'None',
	Farm = 'Farm',
	Clear = 'Clear',
	Factory = 'Factory',
	Road = 'Road',
	Tank = 'Tank',
	Patrol = 'Patrol',
	Truck = 'Truck',
	TruckOrder = 'TruckOrder',
	BorderShield = 'BorderShield',
	Defense = 'Defense',
	Heal = 'Heal',
	HealUnit = 'HealUnit',
	Reactor = 'Reactor',
	Energy = 'Energy',
	Raid = 'Raid',
	Shield = 'Shield',
	DiamondRoad = 'DiamondRoad',
	SpeedUp = 'SpeedUp',
	PowerUp = 'PowerUp',
	FoeReactor = 'FoeReactor',
	ReactorShield = 'ReactorShield',
	DiamondRoadCleaning = 'DiamondRoadCleaning'
}
