export const AudioContent = {
	nok: './sounds/nok.ogg',
	unitPopup: './sounds/unitPopup.wav',
	unitPopup2: './sounds/shotNoise.wav',
	fieldPopup: './sounds/fieldPopup.mp3',
	ok: './sounds/ok.ogg',
	selection: './sounds/selection.wav',
	explosion: './sounds/explosion.wav',
	tankMoving: './sounds/tankMoving.wav',
	death: './sounds/death.ogg',
	death2: './sounds/death2.wav',
	shot: './sounds/shot.wav',
	shot2: './sounds/shot2.wav',
	shot3: './sounds/shot3.wav',
	powerUp: './sounds/powerup.wav',
	noMoney: './sounds/noMoney.wav',
	forestMusic: './sounds/Blazer Rail.wav',
	sandMusic: './sounds/Marimba Boy.wav',
	iceMusic: './sounds/Bobber Loop.wav',
	menuMusic: './sounds/Lounge Game2.wav'
};
