export const Archive = {
    menu:{
        topMenu:'./menu/topMenu.svg',
        bottomMenu:'./menu/bottomMenu.svg',
        backgroundButton:'./menu/backgroundMenu.svg',
        hoverBackgroundButton:'./menu/selectedBackgroundMenu.svg',
        powerButton:'./menu/powerMenu.svg',
        healthButton:'./menu/healthMenu.svg',
        moneyButton:'./menu/moneyMenu.svg',
        speedMenu:'./menu/speedMenu.svg',
        visionMenu:'./menu/visionMenu.svg',
        camouflageMenu:'./menu/camouflageMenu.svg',
        patrolButton:'./menu/patrolButton.svg',
        targetButton:'./menu/targetButton.svg',
        cancelButton:'./menu/cancelButton.svg',
        tankButton:'./menu/tankButton.svg',
        truckButton:'./menu/truckButton.svg',
        zoomInButton:'./menu/zoomInButton.svg',
        zoomOutButton:'./menu/zoomOutButton.svg',
    },
    missiles:[
        './tank/missile/missile.svg',
        './tank/missile/missile2.svg',
        './tank/missile/missile3.svg',
        './tank/missile/missile4.svg',
    ],
    cannons:[
        './tank/cannon.svg',
        './tank/cannon1.svg',
        './tank/cannon2.svg',
        './tank/cannon3.svg',
        './tank/cannon4.svg',
    ],
    diamonds:[
        './truck/diamonds/diamonds1.svg',
        './truck/diamonds/diamonds2.svg',
        './truck/diamonds/diamonds3.svg',
        './truck/diamonds/diamonds4.svg',
        './truck/diamonds/diamonds5.svg',
        './truck/diamonds/diamonds6.svg',
    ],
    loading:'./loading.svg',
    hiddenCell:'./hiddenCell.svg',
    halfVisibleCell:'./halfVisibleCell.svg',
    selectionUnit:'./selectionUnit.svg',
    selectionCell:'./selectionCell.svg',
    cell:'./cell.svg',
    diamondCell:'./diamondCell.svg',
    direction:{
        moving:'./direction/moving1.svg',
        patrol:'./direction/patrol2.svg'
    },
    building:{
        hq:{
            bottom:'./building/hqMiddle.svg',
            top:'./building/hqTop.svg'
        }
    },
    bonus:{
        strength:'./floor/strength.svg',
        speed:'./floor/speed.svg',
        health:'./floor/health.svg',
        emptyMoney:'./floor/money.svg',
        fullMoney:'./floor/money2.svg',
    },
    lights:[
        './lights/light1.svg',
        './lights/light2.svg',
        './lights/light3.svg',
        './lights/light4.svg'
    ],
    nature:{
        diamondStone:'./nature/diamondStone.svg',
        stone:'./nature/stones.svg',
        puddle:'./nature/waterPuddle.svg',
        bush:'./nature/bush.svg',
        rock:'./nature/rock.svg',
        grass:'./nature/grass.svg',
        tree:'./nature/tree.svg',
        water:{
            leaf:'./nature/waterleaf.svg',
            middle:{
                background:'./nature/water.svg',
                wave:'./nature/wave.svg'
            },
            upLeft:{

            },
            downRight:{

            }
        },
        diamond:'./nature/diamond.svg',
    },
    team:{
        red:{
            tank:'./tank/bottomTank.svg',
            turrel:'./tank/redTurrel.svg',
            truck:'./truck/truck.svg',
            hq:'./building/redHqBottom.svg'
        },
        blue:{
            tank:'./tank/blueBottomTank.svg',
            turrel:'./tank/blueTurrel.svg',
            truck:'./truck/blueTruck.svg',
            hq:'./building/blueHqBottom.svg'
        },
        yellow:{
            tank:'./tank/yellowBottomTank.svg',
            turrel:'./tank/yellowTurrel.svg',
            truck:'./truck/yellowTruck.svg',
            hq:'./building/yellowHqBottom.svg'
        }
    },
    wheel:'./tank/wheel.svg',
    wheels:[
        './tank/wheel1.svg',
        './tank/wheel2.svg',
        './tank/wheel3.svg',
        './tank/wheel4.svg',
        './tank/wheel5.svg',
        './tank/wheel6.svg',
        './tank/wheel7.svg',
        './tank/wheel8.svg',
    ]
};
